// src/components/ToolsBar.tsx
import type { Component } from 'solid-js'
import { Icon } from '@iconify-icon/solid'

const ToolButton: Component<{
  name: string
  icon: string
  onClick: () => void
}> = (props) => {
  return (
    <button
      class="
        flex cursor-pointer items-center gap-1 rounded-xl p-2 text-base-content
        hover:bg-base-300
      "
      onClick={() => props.onClick()}
    >
      <Icon icon={props.icon} />
      <span class="text-sm">{props.name}</span>
    </button>
  )
}

const ToolsBar: Component = () => {
  return (
    <div class="
      flex h-12 w-fit items-center gap-1 rounded-xl bg-base-100 px-2 py-1
      shadow-lg ring ring-base-300
    "
    >
      <ToolButton name="Layers" icon="lucide:layers" onClick={() => {}} />
      <ToolButton name="Macros" icon="lucide:zap" onClick={() => {}} />
      <ToolButton name="Combos" icon="lucide:combine" onClick={() => {}} />
      <ToolButton name="Wireless" icon="lucide:bluetooth" onClick={() => {}} />
      <ToolButton name="Firmware" icon="lucide:cpu" onClick={() => {}} />
      <ToolButton name="Setting" icon="lucide:settings" onClick={() => {}} />
    </div>
  )
}

export default ToolsBar

// src/components/ToolsBar.svelte
<script lang='ts'>
  import Icon from '@iconify/svelte'

  function noop() {}
</script>

{#snippet toolButton(name: string, icon: string)}
  <button
    class='
      flex cursor-pointer items-center gap-1 rounded-xl p-2 text-base-content
      hover:bg-base-300
    '
    onclick={noop}
  >
    <Icon {icon} />
    <span class='text-sm'>{name}</span>
  </button>
{/snippet}

<div
  class='
    flex h-12 w-fit items-center gap-1 rounded-xl bg-base-100 px-2 py-1
    shadow-lg ring ring-base-300
  '
>
  {@render toolButton('Layers', 'lucide:layers')}
  {@render toolButton('Macros', 'lucide:zap')}
  {@render toolButton('Combos', 'lucide:combine')}
  {@render toolButton('Wireless', 'lucide:bluetooth')}
  {@render toolButton('Firmware', 'lucide:cpu')}
  {@render toolButton('Setting', 'lucide:settings')}
</div>
