// src/App.tsx
import type { Component } from 'solid-js'
import { onMount } from 'solid-js'
import Keyboard from './components/Keyboard'
import StateBar from './components/StateBar'
import ToolsBar from './components/ToolsBar'
import { ModalProvider } from './hooks/useModal'
import { ToastProvider } from './hooks/useToast'
import { discover } from './rynk'
import { initKbdStore, kbdStore } from './store'

const App: Component = () => {
  onMount(async () => {
    const devices = await discover()
    if (!devices.length) return
    const connected = await devices[0].connect()
    await initKbdStore(connected)
    console.warn('init', kbdStore)
  })

  return <>
    <div class="
      flex h-screen w-screen flex-col items-center gap-4 grid-canvas p-8
    "
    >
      <ToolsBar />
      <div class="w-full flex-1 overflow-auto">
        <Keyboard />
      </div>
      <StateBar />
    </div>
    <ModalProvider />
    <ToastProvider />
  </>
}

export default App

// src/App.svelte
<script lang='ts'>
  import Keyboard from './components/Keyboard.svelte'
  import StateBar from './components/StateBar.svelte'
  import ToolsBar from './components/ToolsBar.svelte'
  import PageHost from './lib/PageHost.svelte'
  import Toaster from './lib/Toaster.svelte'
  import { discover } from './rynk'
  import { keyboardStore } from './stores'

  $effect(() => {
    void (async () => {
      const devices = await discover()
      if (!devices.length) return
      const connected = await devices[0]!.connect()
      await keyboardStore.initStore(connected)
      console.warn('init', keyboardStore)
    })()
  })
</script>

<div class='flex h-screen w-screen flex-col items-center gap-4 grid-canvas p-8'>
  <ToolsBar />
  <div class='w-full flex-1 overflow-auto'>
    <Keyboard />
  </div>
  <StateBar />
</div>

<PageHost />

<Toaster />
